### ISSUE TITLE
Use of media queries

### ISSUE THREAD

**Issue by justsee** [socialally/aqua#4]
The default h element styles include `@media` rules which override any `h*-block` values specified.

The options I can see are:
- include the `h*-block` directives in these media query rules. The example library page has some basic responsive styles, but as soon as a library user defines vars it is the user's responsibility to define appropriate responsive media queries.
- remove any media queries from the project, leaving it up to a library user to define basic styling beyond a smaller viewport

Are there any other considerations or alternatives here?

**Comment by tmpfs** [comment]
Currently, the only media queries are as you say applied to the headers I will separate these declarations to a separate import, load them in the templates so we get some basic responsive styling by default and then developers can remove these queries (by removing or commenting the `@import`).

They are really only declared so the templates look fine on smaller devices.
